### Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9,0])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [3]:
a.reshape(2,5)

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [4]:
a.reshape(2,5,1)

array([[[1],
        [2],
        [3],
        [4],
        [5]],

       [[6],
        [7],
        [8],
        [9],
        [0]]])

In [5]:
# concatenation
a1 = np.array([1,2,3,4])
a2 = np.array([6,7,8,9,10])

In [6]:
np.concatenate((a1,a2))

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10])

In [7]:
a3 = np.array([[1,2,3],[5,6,7]])

In [8]:
np.concatenate((a1,a3))

ValueError: all the input arrays must have same number of dimensions

In [9]:
a4 = np.array([[4,6,7],[9,2,3]])
a4

array([[4, 6, 7],
       [9, 2, 3]])

In [10]:
a3

array([[1, 2, 3],
       [5, 6, 7]])

In [11]:
np.concatenate((a3,a4))

array([[1, 2, 3],
       [5, 6, 7],
       [4, 6, 7],
       [9, 2, 3]])

In [12]:
np.concatenate((a3,a4),axis=1)

array([[1, 2, 3, 4, 6, 7],
       [5, 6, 7, 9, 2, 3]])

In [13]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [14]:
a3

array([[1, 2, 3],
       [5, 6, 7]])

In [15]:
np.min(a3) # minimum element

1

In [16]:
np.max(a3)

7

In [17]:
np.argmin(a3) # index value minimum element

0

In [18]:
np.argmax(a3)

5

In [19]:
np.mean(a3)

4.0

In [20]:
np.median(a3)

4.0

In [21]:
np.average(a3)

4.0

In [22]:
np.var(a3) # variance

4.666666666666667

In [23]:
np.std(a3) # stanard deviation

2.160246899469287

In [24]:
np.sum(a3)

24

In [25]:
a3

array([[1, 2, 3],
       [5, 6, 7]])

In [26]:
np.cumsum(a3) # cumulative sum

array([ 1,  3,  6, 11, 17, 24], dtype=int32)

In [27]:
a3

array([[1, 2, 3],
       [5, 6, 7]])

In [28]:
np.min(a3)

1

In [29]:
np.min(a3,axis=1)  # 1-- rows

array([1, 5])

In [30]:
# axis :  1---rows
#          0--- columns

In [31]:
np.min(a3,axis=0)

array([1, 2, 3])

In [32]:
np.max(a3,axis=1)  # 1-- rows

array([3, 7])

In [33]:
np.argmax(a3,axis=0)

array([1, 1, 1], dtype=int64)

In [34]:
np.argmax(a3,0)

array([1, 1, 1], dtype=int64)

In [35]:
np.min(a3[1])

5

In [36]:
a3[1]

array([5, 6, 7])

In [37]:
a3

array([[1, 2, 3],
       [5, 6, 7]])

In [38]:
# stacking - arranging elements in proper order

# horizontal stacking
# vertical stacking

In [39]:
a3

array([[1, 2, 3],
       [5, 6, 7]])

In [40]:
np.hstack(a3)

array([1, 2, 3, 5, 6, 7])

In [41]:
np.vstack(a3)

array([[1, 2, 3],
       [5, 6, 7]])

In [42]:
np.sqrt(a3)

array([[1.        , 1.41421356, 1.73205081],
       [2.23606798, 2.44948974, 2.64575131]])

In [43]:
np.exp(a3)

array([[   2.71828183,    7.3890561 ,   20.08553692],
       [ 148.4131591 ,  403.42879349, 1096.63315843]])

In [44]:
np.log(a3)

array([[0.        , 0.69314718, 1.09861229],
       [1.60943791, 1.79175947, 1.94591015]])

In [45]:
np.log2(a3)

array([[0.        , 1.        , 1.5849625 ],
       [2.32192809, 2.5849625 , 2.80735492]])

In [46]:
np.log10(a3)

array([[0.        , 0.30103   , 0.47712125],
       [0.69897   , 0.77815125, 0.84509804]])

In [47]:
np.remainder(a3,4)

array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)

In [48]:
a3

array([[1, 2, 3],
       [5, 6, 7]])

In [49]:
np.divide(a3,4)

array([[0.25, 0.5 , 0.75],
       [1.25, 1.5 , 1.75]])

In [50]:
np.power(a3,2)

array([[ 1,  4,  9],
       [25, 36, 49]], dtype=int32)

In [51]:
np.multiply(a3,5)

array([[ 5, 10, 15],
       [25, 30, 35]])

In [52]:
s = np.array([1+2j,5+6j])
s

array([1.+2.j, 5.+6.j])

In [53]:
print(np.real(s))
print(np.imag(s))

[1. 5.]
[2. 6.]


In [54]:
l = [1,2,3,4]
l*3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [55]:
a3

array([[1, 2, 3],
       [5, 6, 7]])

In [56]:
a3*3

array([[ 3,  6,  9],
       [15, 18, 21]])

### Random methods

In [57]:
np.random.random() # it returns random value between 0 and 1

0.9859560714514989

In [58]:
np.random.random(10)

array([0.77028641, 0.82217241, 0.36857966, 0.99396245, 0.84443301,
       0.46910941, 0.39970311, 0.38324724, 0.19560851, 0.75056124])

In [59]:
np.random.random((2,5,2))

array([[[0.00575808, 0.95422415],
        [0.86996526, 0.67996042],
        [0.30147184, 0.56228083],
        [0.20602066, 0.93946113],
        [0.86006609, 0.40849877]],

       [[0.92378569, 0.74747216],
        [0.07632888, 0.40783029],
        [0.82166701, 0.03081718],
        [0.66702618, 0.13866014],
        [0.90270504, 0.36990381]]])

In [60]:
np.random.randint(5) # range of 5

0

In [61]:
np.random.randint(5,20) 

8

#### Filtering

In [62]:
a = np.array([34,67,56,38,67,90,100,58])

In [63]:
a

array([ 34,  67,  56,  38,  67,  90, 100,  58])

In [64]:
a > 50

array([False,  True,  True, False,  True,  True,  True,  True])

In [65]:
a[a>50]

array([ 67,  56,  67,  90, 100,  58])

In [66]:
l = [34,67,56,38,67,90,100,58]
l

[34, 67, 56, 38, 67, 90, 100, 58]

In [67]:
l>50
#-- 67,56,67,90,100,58

TypeError: '>' not supported between instances of 'list' and 'int'

In [68]:
x = np.arange(25,100)

In [69]:
x

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
       76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92,
       93, 94, 95, 96, 97, 98, 99])

In [70]:
x[x%2==0]

array([26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58,
       60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92,
       94, 96, 98])

In [71]:
x[(x>30)&(x<60)]


array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [72]:
x[((x>30)&(x<60))&(x%2==0)]


array([32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [73]:

# | ---or
# !----not

### Pandas

- import/exportthe datsets
- analysize and manipulate the data

[Differnt types of files](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html)

#### Types:
    - Series
        - list,tuple,numpy array
    - DataFrame
        - list,tuple,dict,numpy array
- Datatypes -- float,int,string/object


In [74]:
import pandas as pd

In [ ]:
# pip install pandas
# pip install numpy

In [ ]:
pip install pandas

In [75]:
z = pd.Series([1,2,3,4])
z

0    1
1    2
2    3
3    4
dtype: int64

In [76]:
pd.Series((89,0.8,8))

0    89.0
1     0.8
2     8.0
dtype: float64

In [77]:
pd.Series(np.array([1,2,3,4]))

0    1
1    2
2    3
3    4
dtype: int32

In [78]:
a3

array([[1, 2, 3],
       [5, 6, 7]])

In [79]:
pd.Series(a3)

Exception: Data must be 1-dimensional

In [80]:
v = pd.Series([2,"mvgr",90],index=["a","b","c"])
v

a       2
b    mvgr
c      90
dtype: object

In [81]:
v.index

Index(['a', 'b', 'c'], dtype='object')

In [82]:
v = pd.Series([2,"mvgr",90],index=["a","b","c"],columns=["ap"])
v

TypeError: __init__() got an unexpected keyword argument 'columns'

In [83]:
pd.Series({"a":[67,89,90],"b":90})

a    [67, 89, 90]
b              90
dtype: object

In [84]:
a3

array([[1, 2, 3],
       [5, 6, 7]])

In [85]:
d = pd.DataFrame(a3,index = ["a",5],columns=["mvgr","raghu","gates"])
d

mvgr  raghu  gates
a     1      2      3
5     5      6      7

In [86]:
d

mvgr  raghu  gates
a     1      2      3
5     5      6      7

In [87]:
pd.DataFrame({"a":[67,89,90],"b":90})

a   b
0  67  90
1  89  90
2  90  90

In [88]:
pd.Series({"a":[67,89,90],"b":90})

a    [67, 89, 90]
b              90
dtype: object

In [89]:
pd.DataFrame([[1,2,3],[5,6]],index=("a","b"),columns = ("x","y","z"))

x  y    z
a  1  2  3.0
b  5  6  NaN

In [90]:
#pd.DataFrame(((2,5,6),(5,8,90)),index=(1,2),columns=("a","h","c"))


In [92]:
#pd.DataFrame(((2,5,6),(5,8,90)),index=(1,2),columns=("a","h","c"))

In [93]:
d = {"Name":["apssdc","workshop"],"date":[12,6],"year":[2012,2013]}

In [97]:
d1 = pd.DataFrame(d,index=["a","b"])

In [98]:
d1

Name  date  year
a    apssdc    12  2012
b  workshop     6  2013

In [99]:
d1.columns

Index(['Name', 'date', 'year'], dtype='object')

In [100]:
d1.index

Index(['a', 'b'], dtype='object')

In [101]:
d1.shape

(2, 3)

In [102]:
# Accessing the elements

In [103]:
d1["Name"]

a      apssdc
b    workshop
Name: Name, dtype: object

In [106]:
d1["year"]

a    2012
b    2013
Name: year, dtype: int64

In [109]:
d1.year

a    2012
b    2013
Name: year, dtype: int64

In [108]:
d1[["Name","year"]]

Name  year
a    apssdc  2012
b  workshop  2013

In [112]:
d1["Name"]["b"]

'workshop'

In [113]:
d1["Name"][1]

'workshop'

In [114]:
d1["Name"]

a      apssdc
b    workshop
Name: Name, dtype: object

In [115]:
d1

Name  date  year
a    apssdc    12  2012
b  workshop     6  2013

In [117]:
d1[1:]

Name  date  year
b  workshop     6  2013

In [121]:
d1[-1:]

Name  date  year
b  workshop     6  2013