## Data Analysis

In [1]:
# Modules
print(help("modules"))


Please wait a moment while I gather a list of all available modules...



C:\Users\Alekhya\Anaconda3\lib\site-packages\IPython\kernel\__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
C:\Users\Alekhya\Anaconda3\lib\site-packages\dask\config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
C:\Users\Alekhya\Anaconda3\lib\site-packages\distributed\config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)
C:\Users\Alekhya\Anaconda3\lib\site-packages\nltk\twitter\__init__.py:22: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not b

DEBUG:pip._internal.vcs.versioncontrol:Registered VCS backend: bzr
DEBUG:pip._internal.vcs.versioncontrol:Registered VCS backend: git
DEBUG:pip._internal.vcs.versioncontrol:Registered VCS backend: hg
DEBUG:pip._internal.vcs.versioncontrol:Registered VCS backend: svn


C:\Users\Alekhya\Anaconda3\lib\site-packages\skimage\novice\__init__.py:103: UserWarning: The `skimage.novice` module was deprecated in version 0.14. It will be removed in 0.16.
  warnings.warn("The `skimage.novice` module was deprecated in version 0.14. "
C:\Users\Alekhya\Anaconda3\lib\site-packages\skimage\viewer\utils\core.py:10: UserWarning: Recommended matplotlib backend is `Agg` for full skimage.viewer functionality.
  warn("Recommended matplotlib backend is `Agg` for full "
C:\Users\Alekhya\Anaconda3\lib\site-packages\sphinx\websupport\__init__.py:25: RemovedInSphinx20Warning: sphinx.websupport module is now provided as sphinxcontrib-websupport. sphinx.websupport will be removed at Sphinx-2.0. Please use the package instead.
  RemovedInSphinx20Warning)
C:\Users\Alekhya\Anaconda3\lib\site-packages\qtawesome\iconic_font.py:276: UserWarning: You need to have a running QApplication to use QtAwesome!
  warnings.warn("You need to have a running "
C:\Users\Alekhya\Anaconda3\lib\pkgutil

Crypto              bz2                 menuinst            sortedcollections
Cython              cProfile            mimetypes           sortedcontainers
IPython             calendar            mistune             soupsieve
OpenSSL             certifi             mkl                 sphinx
PIL                 cffi                mkl_fft             sphinxcontrib
PyQt5               cgi                 mkl_random          spyder
__future__          cgitb               mmap                spyder_breakpoints
_abc                chardet             mmapfile            spyder_io_dcm
_ast                chunk               mmsystem            spyder_io_hdf5
_asyncio            click               modulefinder        spyder_kernels
_bisect             cloudpickle         more_itertools      spyder_profiler
_blake2             clyent              mpmath              spyder_pylint
_bootlocale         cmath               msgpack             sqlalchemy
_bz2                cmd                 msi

autoreload          inspect             quopri              win32ras
babel               io                  random              win32rcparser
backcall            ipaddress           rasutil             win32security
backports           ipykernel           re                  win32service
base64              ipykernel_launcher  readline            win32serviceutil
bcrypt              ipython_genutils    regcheck            win32timezone
bdb                 ipywidgets          regutil             win32trace
binascii            isapi               reprlib             win32traceutil
binhex              isort               requests            win32transaction
binstar_client      isympy              rlcompleter         win32ts
bisect              itertools           rmagic              win32ui
bitarray            itsdangerous        rope                win32uiole
bkcharts            jdcal               ruamel_yaml         win32verstamp
blaze               jedi                run            

In [2]:
# packages
pip list

Package                            Version
---------------------------------- ---------
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.9.7
anaconda-project                   0.8.2
appdirs                            1.4.4
asn1crypto                         0.24.0
astroid                            2.2.5
astropy                            3.1.2
atomicwrites                       1.3.0
attrs                              19.1.0
Automat                            20.2.0
Babel                              2.6.0
backcall                           0.1.0
backports.os                       0.1.1
backports.shutil-get-terminal-size 1.0.0
bcrypt                             3.1.6
beautifulsoup4                     4.7.1
bitarray                           0.8.3
bkcharts                           0.2
blaze                              0.11.3
bleach                             3.1.0
bokeh                              1.0.4
boto   

terminado                          0.8.1
testpath                           0.4.2
toolz                              0.9.0
tornado                            6.0.2
tqdm                               4.31.1
traitlets                          4.3.2
Twisted                            19.2.0
unicodecsv                         0.14.1
urllib3                            1.24.1
wcwidth                            0.1.7
webencodings                       0.5.1
Werkzeug                           0.14.1
wheel                              0.33.1
widgetsnbextension                 3.4.2
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.11.1
xlrd                               1.2.0
XlsxWriter                         1.1.5
xlwings                            0.15.4
xlwt                               1.3.0
zict                               0.1.4
zipp                               0.3.3
zope.interfa

You should consider upgrading via the 'C:\Users\Alekhya\Anaconda3\python.exe -m pip install --upgrade pip' command.


Note: you may need to restart the kernel to use updated packages.


## Numpy- Numerical Python

In [3]:
import numpy as np

In [4]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [6]:
help(np.vstack)

Help on function vstack in module numpy:

vstack(tup)
    Stack arrays in sequence vertically (row wise).
    
    This is equivalent to concatenation along the first axis after 1-D arrays
    of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
    `vsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the first axis.
        1-D arrays must have the same length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays, will be at least 2-D.
    
    See Also
    --------
    stack : Join a sequence of arrays along a new axis.
    hstack

In [7]:
a = np.array([1,2,3,4])

In [8]:
a

array([1, 2, 3, 4])

In [9]:
a.ndim # it will find outs which dimension

1

In [10]:
a.dtype # data type

dtype('int32')

In [11]:
b = np.array(["apssdc"])
b.dtype

dtype('<U6')

In [12]:
c = np.array([1,"apssdc",5.6])
c

array(['1', 'apssdc', '5.6'], dtype='<U11')

In [15]:
a = np.append(a,[1,2,3])

In [16]:
a

array([1, 2, 3, 4, 1, 2, 3])

In [19]:
range(1,10,0.5)

TypeError: 'float' object cannot be interpreted as an integer

In [23]:
np.arange(1,23.5,0.5) # start,end(exclusive),step

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5, 22. , 22.5,
       23. ])

In [25]:
x = np.linspace(1,100,34) # start,ending(inclusive),number of divisions/parts

In [26]:
x

array([  1.,   4.,   7.,  10.,  13.,  16.,  19.,  22.,  25.,  28.,  31.,
        34.,  37.,  40.,  43.,  46.,  49.,  52.,  55.,  58.,  61.,  64.,
        67.,  70.,  73.,  76.,  79.,  82.,  85.,  88.,  91.,  94.,  97.,
       100.])

In [27]:
x.ndim

1

In [28]:
len(x)

34

In [29]:
x.itemsize

8

In [30]:
x.nbytes

272

In [32]:
np.full(10,23)

array([23, 23, 23, 23, 23, 23, 23, 23, 23, 23])

In [33]:
np.full(10,"a")

array(['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a'], dtype='<U1')

In [34]:
## 2d- array

b = np.array([[1,2,3],[3,4,5]])
b

array([[1, 2, 3],
       [3, 4, 5]])

In [35]:
b.ndim

2

In [38]:
### 3d -array
c = np.array([[[1,2,3],[3,4,5]],[[8,9,10],[7,8,9]]])
c

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 8,  9, 10],
        [ 7,  8,  9]]])

In [39]:
c.ndim

3

In [40]:
a

array([1, 2, 3, 4, 1, 2, 3])

In [41]:
b #(2,3)

array([[1, 2, 3],
       [3, 4, 5]])

In [42]:
c #(2,2,3) positions,rows,columns

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 8,  9, 10],
        [ 7,  8,  9]]])

In [43]:
d = np.array([[8,9,10],[4,5,6]])
d

array([[ 8,  9, 10],
       [ 4,  5,  6]])

In [44]:
x = np.array([b,d])

In [45]:
x

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 8,  9, 10],
        [ 4,  5,  6]]])

In [46]:
a

array([1, 2, 3, 4, 1, 2, 3])

In [47]:
a[3]

4

In [48]:
a[-1]

3

In [50]:
a[2:4]

array([3, 4])

In [49]:
b

array([[1, 2, 3],
       [3, 4, 5]])

In [52]:
b[1][2]

5

In [53]:
b[1,2] # row index and column index

5

In [56]:
b[:,2:]

array([[3],
       [5]])

In [57]:
b[1:,1:]

array([[4, 5]])

In [58]:
c

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 8,  9, 10],
        [ 7,  8,  9]]])

In [59]:
c[1,0,1]

9

In [60]:
c[0,1,1]

4

In [61]:
c[0]

array([[1, 2, 3],
       [3, 4, 5]])

In [62]:
c[1]

array([[ 8,  9, 10],
       [ 7,  8,  9]])

In [63]:
c

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 8,  9, 10],
        [ 7,  8,  9]]])

In [64]:
c[:,1,1]

array([4, 8])

In [65]:
c[:,:,2:]

array([[[ 3],
        [ 5]],

       [[10],
        [ 9]]])

In [66]:
c[:,:,-1:]

array([[[ 3],
        [ 5]],

       [[10],
        [ 9]]])

In [67]:
# reshaping an array

In [68]:
a

array([1, 2, 3, 4, 1, 2, 3])

In [69]:
a.shape

(7,)

In [71]:
b.shape

(2, 3)

In [72]:
c.shape

(2, 2, 3)

In [73]:
a.reshape(2,4)

ValueError: cannot reshape array of size 7 into shape (2,4)

In [74]:
a.reshape(2,3)

ValueError: cannot reshape array of size 7 into shape (2,3)

In [76]:
x = a.reshape(1,7)

In [77]:
x

array([[1, 2, 3, 4, 1, 2, 3]])

In [84]:
x[0,3]

4

In [80]:
a

array([1, 2, 3, 4, 1, 2, 3])

In [81]:
a[3]

4

In [78]:
x.ndim

2

In [79]:
a.reshape(7,1)

array([[1],
       [2],
       [3],
       [4],
       [1],
       [2],
       [3]])

In [85]:
a.reshape(1,-1)

array([[1, 2, 3, 4, 1, 2, 3]])

In [86]:
a.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [1],
       [2],
       [3]])

In [87]:
a.reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [88]:
a.reshape(2,-1)

ValueError: cannot reshape array of size 7 into shape (2,newaxis)

In [89]:
f = np.array([1,2,3,4,5,6])
f

array([1, 2, 3, 4, 5, 6])

In [90]:
f.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [91]:
f.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
f.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [93]:
f.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [94]:
f.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
f.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [97]:
f.reshape(4,-1)

ValueError: cannot reshape array of size 6 into shape (4,newaxis)

In [98]:
s = np.array([1,2,3,4,5,6,7,8,9,10])
s

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
s.reshape(10,1,1)

array([[[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]]])

In [100]:
s.reshape(5,2,1)

array([[[ 1],
        [ 2]],

       [[ 3],
        [ 4]],

       [[ 5],
        [ 6]],

       [[ 7],
        [ 8]],

       [[ 9],
        [10]]])